'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
'
Namespace br.com.correios.ws
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="CalcPrecoPrazoWSSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CalcPrecoPrazoWS
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CalcPrecoPrazoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CalcPrecoPrazoDataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CalcPrecoPrazoRestricaoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CalcPrecoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CalcPrecoDataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CalcPrazoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CalcPrazoDataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CalcPrazoRestricaoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CalcPrecoFACOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Calcular_Frete_VB.My.MySettings.Default.Calcular_Frete_VB_br_com_correios_ws_CalcPrecoPrazoWS
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CalcPrecoPrazoCompleted As CalcPrecoPrazoCompletedEventHandler
        
        '''<remarks/>
        Public Event CalcPrecoPrazoDataCompleted As CalcPrecoPrazoDataCompletedEventHandler
        
        '''<remarks/>
        Public Event CalcPrecoPrazoRestricaoCompleted As CalcPrecoPrazoRestricaoCompletedEventHandler
        
        '''<remarks/>
        Public Event CalcPrecoCompleted As CalcPrecoCompletedEventHandler
        
        '''<remarks/>
        Public Event CalcPrecoDataCompleted As CalcPrecoDataCompletedEventHandler
        
        '''<remarks/>
        Public Event CalcPrazoCompleted As CalcPrazoCompletedEventHandler
        
        '''<remarks/>
        Public Event CalcPrazoDataCompleted As CalcPrazoDataCompletedEventHandler
        
        '''<remarks/>
        Public Event CalcPrazoRestricaoCompleted As CalcPrazoRestricaoCompletedEventHandler
        
        '''<remarks/>
        Public Event CalcPrecoFACCompleted As CalcPrecoFACCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalcPrecoPrazo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CalcPrecoPrazo(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String) As cResultado
            Dim results() As Object = Me.Invoke("CalcPrecoPrazo", New Object() {nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento})
            Return CType(results(0),cResultado)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CalcPrecoPrazoAsync(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String)
            Me.CalcPrecoPrazoAsync(nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CalcPrecoPrazoAsync(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal userState As Object)
            If (Me.CalcPrecoPrazoOperationCompleted Is Nothing) Then
                Me.CalcPrecoPrazoOperationCompleted = AddressOf Me.OnCalcPrecoPrazoOperationCompleted
            End If
            Me.InvokeAsync("CalcPrecoPrazo", New Object() {nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento}, Me.CalcPrecoPrazoOperationCompleted, userState)
        End Sub
        
        Private Sub OnCalcPrecoPrazoOperationCompleted(ByVal arg As Object)
            If (Not (Me.CalcPrecoPrazoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CalcPrecoPrazoCompleted(Me, New CalcPrecoPrazoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalcPrecoPrazoData", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CalcPrecoPrazoData(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal sDtCalculo As String) As cResultado
            Dim results() As Object = Me.Invoke("CalcPrecoPrazoData", New Object() {nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento, sDtCalculo})
            Return CType(results(0),cResultado)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CalcPrecoPrazoDataAsync(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal sDtCalculo As String)
            Me.CalcPrecoPrazoDataAsync(nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento, sDtCalculo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CalcPrecoPrazoDataAsync( _
                    ByVal nCdEmpresa As String,  _
                    ByVal sDsSenha As String,  _
                    ByVal nCdServico As String,  _
                    ByVal sCepOrigem As String,  _
                    ByVal sCepDestino As String,  _
                    ByVal nVlPeso As String,  _
                    ByVal nCdFormato As Integer,  _
                    ByVal nVlComprimento As Decimal,  _
                    ByVal nVlAltura As Decimal,  _
                    ByVal nVlLargura As Decimal,  _
                    ByVal nVlDiametro As Decimal,  _
                    ByVal sCdMaoPropria As String,  _
                    ByVal nVlValorDeclarado As Decimal,  _
                    ByVal sCdAvisoRecebimento As String,  _
                    ByVal sDtCalculo As String,  _
                    ByVal userState As Object)
            If (Me.CalcPrecoPrazoDataOperationCompleted Is Nothing) Then
                Me.CalcPrecoPrazoDataOperationCompleted = AddressOf Me.OnCalcPrecoPrazoDataOperationCompleted
            End If
            Me.InvokeAsync("CalcPrecoPrazoData", New Object() {nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento, sDtCalculo}, Me.CalcPrecoPrazoDataOperationCompleted, userState)
        End Sub
        
        Private Sub OnCalcPrecoPrazoDataOperationCompleted(ByVal arg As Object)
            If (Not (Me.CalcPrecoPrazoDataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CalcPrecoPrazoDataCompleted(Me, New CalcPrecoPrazoDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalcPrecoPrazoRestricao", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CalcPrecoPrazoRestricao(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal sDtCalculo As String) As cResultado
            Dim results() As Object = Me.Invoke("CalcPrecoPrazoRestricao", New Object() {nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento, sDtCalculo})
            Return CType(results(0),cResultado)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CalcPrecoPrazoRestricaoAsync(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal sDtCalculo As String)
            Me.CalcPrecoPrazoRestricaoAsync(nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento, sDtCalculo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CalcPrecoPrazoRestricaoAsync( _
                    ByVal nCdEmpresa As String,  _
                    ByVal sDsSenha As String,  _
                    ByVal nCdServico As String,  _
                    ByVal sCepOrigem As String,  _
                    ByVal sCepDestino As String,  _
                    ByVal nVlPeso As String,  _
                    ByVal nCdFormato As Integer,  _
                    ByVal nVlComprimento As Decimal,  _
                    ByVal nVlAltura As Decimal,  _
                    ByVal nVlLargura As Decimal,  _
                    ByVal nVlDiametro As Decimal,  _
                    ByVal sCdMaoPropria As String,  _
                    ByVal nVlValorDeclarado As Decimal,  _
                    ByVal sCdAvisoRecebimento As String,  _
                    ByVal sDtCalculo As String,  _
                    ByVal userState As Object)
            If (Me.CalcPrecoPrazoRestricaoOperationCompleted Is Nothing) Then
                Me.CalcPrecoPrazoRestricaoOperationCompleted = AddressOf Me.OnCalcPrecoPrazoRestricaoOperationCompleted
            End If
            Me.InvokeAsync("CalcPrecoPrazoRestricao", New Object() {nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento, sDtCalculo}, Me.CalcPrecoPrazoRestricaoOperationCompleted, userState)
        End Sub
        
        Private Sub OnCalcPrecoPrazoRestricaoOperationCompleted(ByVal arg As Object)
            If (Not (Me.CalcPrecoPrazoRestricaoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CalcPrecoPrazoRestricaoCompleted(Me, New CalcPrecoPrazoRestricaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalcPreco", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CalcPreco(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String) As cResultado
            Dim results() As Object = Me.Invoke("CalcPreco", New Object() {nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento})
            Return CType(results(0),cResultado)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CalcPrecoAsync(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String)
            Me.CalcPrecoAsync(nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CalcPrecoAsync(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal userState As Object)
            If (Me.CalcPrecoOperationCompleted Is Nothing) Then
                Me.CalcPrecoOperationCompleted = AddressOf Me.OnCalcPrecoOperationCompleted
            End If
            Me.InvokeAsync("CalcPreco", New Object() {nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento}, Me.CalcPrecoOperationCompleted, userState)
        End Sub
        
        Private Sub OnCalcPrecoOperationCompleted(ByVal arg As Object)
            If (Not (Me.CalcPrecoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CalcPrecoCompleted(Me, New CalcPrecoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalcPrecoData", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CalcPrecoData(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal sDtCalculo As String) As cResultado
            Dim results() As Object = Me.Invoke("CalcPrecoData", New Object() {nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento, sDtCalculo})
            Return CType(results(0),cResultado)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CalcPrecoDataAsync(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal sDtCalculo As String)
            Me.CalcPrecoDataAsync(nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento, sDtCalculo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CalcPrecoDataAsync( _
                    ByVal nCdEmpresa As String,  _
                    ByVal sDsSenha As String,  _
                    ByVal nCdServico As String,  _
                    ByVal sCepOrigem As String,  _
                    ByVal sCepDestino As String,  _
                    ByVal nVlPeso As String,  _
                    ByVal nCdFormato As Integer,  _
                    ByVal nVlComprimento As Decimal,  _
                    ByVal nVlAltura As Decimal,  _
                    ByVal nVlLargura As Decimal,  _
                    ByVal nVlDiametro As Decimal,  _
                    ByVal sCdMaoPropria As String,  _
                    ByVal nVlValorDeclarado As Decimal,  _
                    ByVal sCdAvisoRecebimento As String,  _
                    ByVal sDtCalculo As String,  _
                    ByVal userState As Object)
            If (Me.CalcPrecoDataOperationCompleted Is Nothing) Then
                Me.CalcPrecoDataOperationCompleted = AddressOf Me.OnCalcPrecoDataOperationCompleted
            End If
            Me.InvokeAsync("CalcPrecoData", New Object() {nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento, sDtCalculo}, Me.CalcPrecoDataOperationCompleted, userState)
        End Sub
        
        Private Sub OnCalcPrecoDataOperationCompleted(ByVal arg As Object)
            If (Not (Me.CalcPrecoDataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CalcPrecoDataCompleted(Me, New CalcPrecoDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalcPrazo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CalcPrazo(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String) As cResultado
            Dim results() As Object = Me.Invoke("CalcPrazo", New Object() {nCdServico, sCepOrigem, sCepDestino})
            Return CType(results(0),cResultado)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CalcPrazoAsync(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String)
            Me.CalcPrazoAsync(nCdServico, sCepOrigem, sCepDestino, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CalcPrazoAsync(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal userState As Object)
            If (Me.CalcPrazoOperationCompleted Is Nothing) Then
                Me.CalcPrazoOperationCompleted = AddressOf Me.OnCalcPrazoOperationCompleted
            End If
            Me.InvokeAsync("CalcPrazo", New Object() {nCdServico, sCepOrigem, sCepDestino}, Me.CalcPrazoOperationCompleted, userState)
        End Sub
        
        Private Sub OnCalcPrazoOperationCompleted(ByVal arg As Object)
            If (Not (Me.CalcPrazoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CalcPrazoCompleted(Me, New CalcPrazoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalcPrazoData", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CalcPrazoData(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal sDtCalculo As String) As cResultado
            Dim results() As Object = Me.Invoke("CalcPrazoData", New Object() {nCdServico, sCepOrigem, sCepDestino, sDtCalculo})
            Return CType(results(0),cResultado)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CalcPrazoDataAsync(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal sDtCalculo As String)
            Me.CalcPrazoDataAsync(nCdServico, sCepOrigem, sCepDestino, sDtCalculo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CalcPrazoDataAsync(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal sDtCalculo As String, ByVal userState As Object)
            If (Me.CalcPrazoDataOperationCompleted Is Nothing) Then
                Me.CalcPrazoDataOperationCompleted = AddressOf Me.OnCalcPrazoDataOperationCompleted
            End If
            Me.InvokeAsync("CalcPrazoData", New Object() {nCdServico, sCepOrigem, sCepDestino, sDtCalculo}, Me.CalcPrazoDataOperationCompleted, userState)
        End Sub
        
        Private Sub OnCalcPrazoDataOperationCompleted(ByVal arg As Object)
            If (Not (Me.CalcPrazoDataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CalcPrazoDataCompleted(Me, New CalcPrazoDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalcPrazoRestricao", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CalcPrazoRestricao(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal sDtCalculo As String) As cResultado
            Dim results() As Object = Me.Invoke("CalcPrazoRestricao", New Object() {nCdServico, sCepOrigem, sCepDestino, sDtCalculo})
            Return CType(results(0),cResultado)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CalcPrazoRestricaoAsync(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal sDtCalculo As String)
            Me.CalcPrazoRestricaoAsync(nCdServico, sCepOrigem, sCepDestino, sDtCalculo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CalcPrazoRestricaoAsync(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal sDtCalculo As String, ByVal userState As Object)
            If (Me.CalcPrazoRestricaoOperationCompleted Is Nothing) Then
                Me.CalcPrazoRestricaoOperationCompleted = AddressOf Me.OnCalcPrazoRestricaoOperationCompleted
            End If
            Me.InvokeAsync("CalcPrazoRestricao", New Object() {nCdServico, sCepOrigem, sCepDestino, sDtCalculo}, Me.CalcPrazoRestricaoOperationCompleted, userState)
        End Sub
        
        Private Sub OnCalcPrazoRestricaoOperationCompleted(ByVal arg As Object)
            If (Not (Me.CalcPrazoRestricaoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CalcPrazoRestricaoCompleted(Me, New CalcPrazoRestricaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalcPrecoFAC", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CalcPrecoFAC(ByVal nCdServico As String, ByVal nVlPeso As String, ByVal strDataCalculo As String) As cResultado
            Dim results() As Object = Me.Invoke("CalcPrecoFAC", New Object() {nCdServico, nVlPeso, strDataCalculo})
            Return CType(results(0),cResultado)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CalcPrecoFACAsync(ByVal nCdServico As String, ByVal nVlPeso As String, ByVal strDataCalculo As String)
            Me.CalcPrecoFACAsync(nCdServico, nVlPeso, strDataCalculo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CalcPrecoFACAsync(ByVal nCdServico As String, ByVal nVlPeso As String, ByVal strDataCalculo As String, ByVal userState As Object)
            If (Me.CalcPrecoFACOperationCompleted Is Nothing) Then
                Me.CalcPrecoFACOperationCompleted = AddressOf Me.OnCalcPrecoFACOperationCompleted
            End If
            Me.InvokeAsync("CalcPrecoFAC", New Object() {nCdServico, nVlPeso, strDataCalculo}, Me.CalcPrecoFACOperationCompleted, userState)
        End Sub
        
        Private Sub OnCalcPrecoFACOperationCompleted(ByVal arg As Object)
            If (Not (Me.CalcPrecoFACCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CalcPrecoFACCompleted(Me, New CalcPrecoFACCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class cResultado
        
        Private servicosField() As cServico
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property Servicos() As cServico()
            Get
                Return Me.servicosField
            End Get
            Set
                Me.servicosField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class cServico
        
        Private codigoField As Integer
        
        Private valorField As String
        
        Private prazoEntregaField As String
        
        Private valorMaoPropriaField As String
        
        Private valorAvisoRecebimentoField As String
        
        Private valorValorDeclaradoField As String
        
        Private entregaDomiciliarField As String
        
        Private entregaSabadoField As String
        
        Private erroField As String
        
        Private msgErroField As String
        
        Private valorSemAdicionaisField As String
        
        Private obsFimField As String
        
        '''<remarks/>
        Public Property Codigo() As Integer
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Valor() As String
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PrazoEntrega() As String
            Get
                Return Me.prazoEntregaField
            End Get
            Set
                Me.prazoEntregaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ValorMaoPropria() As String
            Get
                Return Me.valorMaoPropriaField
            End Get
            Set
                Me.valorMaoPropriaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ValorAvisoRecebimento() As String
            Get
                Return Me.valorAvisoRecebimentoField
            End Get
            Set
                Me.valorAvisoRecebimentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ValorValorDeclarado() As String
            Get
                Return Me.valorValorDeclaradoField
            End Get
            Set
                Me.valorValorDeclaradoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EntregaDomiciliar() As String
            Get
                Return Me.entregaDomiciliarField
            End Get
            Set
                Me.entregaDomiciliarField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EntregaSabado() As String
            Get
                Return Me.entregaSabadoField
            End Get
            Set
                Me.entregaSabadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Erro() As String
            Get
                Return Me.erroField
            End Get
            Set
                Me.erroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MsgErro() As String
            Get
                Return Me.msgErroField
            End Get
            Set
                Me.msgErroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ValorSemAdicionais() As String
            Get
                Return Me.valorSemAdicionaisField
            End Get
            Set
                Me.valorSemAdicionaisField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property obsFim() As String
            Get
                Return Me.obsFimField
            End Get
            Set
                Me.obsFimField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub CalcPrecoPrazoCompletedEventHandler(ByVal sender As Object, ByVal e As CalcPrecoPrazoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CalcPrecoPrazoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As cResultado
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),cResultado)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub CalcPrecoPrazoDataCompletedEventHandler(ByVal sender As Object, ByVal e As CalcPrecoPrazoDataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CalcPrecoPrazoDataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As cResultado
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),cResultado)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub CalcPrecoPrazoRestricaoCompletedEventHandler(ByVal sender As Object, ByVal e As CalcPrecoPrazoRestricaoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CalcPrecoPrazoRestricaoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As cResultado
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),cResultado)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub CalcPrecoCompletedEventHandler(ByVal sender As Object, ByVal e As CalcPrecoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CalcPrecoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As cResultado
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),cResultado)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub CalcPrecoDataCompletedEventHandler(ByVal sender As Object, ByVal e As CalcPrecoDataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CalcPrecoDataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As cResultado
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),cResultado)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub CalcPrazoCompletedEventHandler(ByVal sender As Object, ByVal e As CalcPrazoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CalcPrazoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As cResultado
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),cResultado)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub CalcPrazoDataCompletedEventHandler(ByVal sender As Object, ByVal e As CalcPrazoDataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CalcPrazoDataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As cResultado
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),cResultado)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub CalcPrazoRestricaoCompletedEventHandler(ByVal sender As Object, ByVal e As CalcPrazoRestricaoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CalcPrazoRestricaoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As cResultado
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),cResultado)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub CalcPrecoFACCompletedEventHandler(ByVal sender As Object, ByVal e As CalcPrecoFACCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CalcPrecoFACCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As cResultado
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),cResultado)
            End Get
        End Property
    End Class
End Namespace
